### PR TITLE
Update version of vuepress

### LINKED ISSUE #73: Update version of vuepress
Vuepress has been updated to a stable version, we should update it and this might probably fix issues we have in the design

### PR DESCRIPTION
**Pull request by mcmxcdev**
After fixing various encountered errors due to updating dependencies, both `build` and `dev` npm scripts work flawless again. 

Additionally, there were no errors encountered when browsing through the project on localhost.

Closes #73.

### CODE REVIEW

**Comment by antho1404** [comment]
Hi @mhatvan, thanks for the work, a few feedback tho:

- Could you make sure that the design matches the current version https://docs.mesg.com/
  - Purple top bar
  - Logo in the top bar
  - Remove the title in the home page
- The sitemap doesn't seem to work 
  - https://deploy-preview-82--mesg-docs.netlify.com/sitemap.xml vs https://docs.mesg.com/sitemap.xml

**Comment by mcmxcdev** [comment]
Oh my bad, I was in a bit of a hurry.
I will match the design and fix the sitemap asap.

**Comment by mcmxcdev** [comment]
@antho1404 Both issues that you reported are fixed now: 
* the purple top bar and other styles were missing because `override.styl` was renamed to `palette.styl` by vuepress
* the sitemap works correctly now in the deploy preview

**Review by antho1404 — APPROVED** [review]

**Comment by mcmxcdev** [comment]
Hey @antho1404, glad to see that you approved the changes! 
Can we get this merged now or is there something else left to do?

**Pull request merged**
